### ISSUE TITLE
no val_loc and train_loc fields in xlsa17

### ISSUE THREAD

**Issue by mdabbah** [hbdat/cvpr20_DAZLE#1]
Hi, 
I have downloaded and extracted xlsa17 from the xlsa17 source site ([link](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly/)) and the link given in  ./data/xlsa17/instruction_xlsa17.txt 
and in both of them, the att_splits.mat does not have the mentioned fields [ val_loc, train_loc]

can you help me? 
Thanks

**Comment by hbdat** [comment]
Hi there,

Thanks for reaching out.
I double check the files again and they did contain the fields (an screenshot from ```/xlsa17/data/CUB/att_splits.mat```) :
![image](https://user-images.githubusercontent.com/60049111/86545076-05679f80-befa-11ea-9e02-df77a15fc890.png)


Did you download from this link:
[http://datasets.d2.mpi-inf.mpg.de/xian/xlsa17.zip](http://datasets.d2.mpi-inf.mpg.de/xian/xlsa17.zip)

Best,
Dat

**Comment by mdabbah** [comment]
wow, this is weird :| 
I've downloaded from this link twice (3 times including the last time haha) 
and I still don't get those fields 
![image](https://user-images.githubusercontent.com/34287255/86670869-c6227700-bffd-11ea-8a9a-628c72d340da.png)
 (screenshot attached)

I've read the good the bad and the ugly paper and I've dealt with the splits they proposed before, 
from my understanding (correct me if I'm wrong), they define the validation classes in text files but they don't define the samples indices for validation (which is what I assume val_loc is)

are train_loc and val_loc derived from trainval_loc and one of those valcalsses.txt files?
Thanks!

**Comment by hbdat** [comment]
Hi there,

As I downloaded the data split from the link, it was indeed missing the validation field in the mat file (which was strange as the data split from the same link I had 2 year ago did contain it).
Regardless, the validation field is not required to run the code. Therefore, I have modified the feature extraction script to exclude this field -- thus can be run without the validation field.

Best,
Dat

**Comment by mdabbah** [comment]
Hi, 
yes, I've noticed that, and commented out the parts of the feature extraction code that refer to it in my local copy in order to run it.
I was just curious about those splits (train validation splits), and how can one obtain them, have they been standardized in recent works as have the seen unseen splits been standardized by xian et al (in the good the bad and the ugly)

**Comment by hbdat** [comment]
Hi there, 
I have answered the question via email. So I will close the thread.
