### ISSUE TITLE
Data type mismatch！

### ISSUE THREAD

**Issue by hzwfl2** [hbdat/cvpr20_DAZLE#2]
I met much trouble with data type mismatch. I think these problems are caused by the different versions of PyTorch or other environments. Can you give the details of your prerequisites (not '.x')? Thanks!

**Comment by hbdat** [comment]
Hi there,

Sorry for the inconvenience. I have committed the list of used packages as well as their versions in the file ```./requirements.txt```.
Please run the following command to install them:
```
pip install -r requirements.txt
```

Best,
Dat
