### ISSUE TITLE
data_transform in extract_feature_map_resnet_101_xxxxx

### ISSUE THREAD

**Issue by RowenaHe** [hbdat/cvpr20_DAZLE#21]
"data_transforms" in folder "extract_feature". You first resize the image to input_size and then centercrop input_size? Is there some mistake? 

transforms.Resize(input_size),
transforms.CenterCrop(input_size),

**Comment by litianjun05090** [comment]
You may need to take a look at pytorch official document 
https://pytorch.org/vision/main/auto_examples/plot_transforms.html#sphx-glr-auto-examples-plot-transforms-py

**Comment by litianjun05090** [comment]
https://pytorch.org/vision/main/auto_examples/plot_transforms.html#sphx-glr-auto-examples-plot-transforms-py

**Comment by RowenaHe** [comment]
@litianjun05090 Thank you for your help! I was not very famaliar with all those python and pytorch functionality and got confused. I've learned it back then. But, still, thank you anyway!
